name: games_server
services:
  tailscale:
    image: tailscale/tailscale:v1.96.5
    hostname: games-server
    container_name: games_server_tailscale
    env_file:
      - .env
    secrets:
      - ts_authkey
    # Replace TS_AUTHKEY with new file env var when tailscale adds support
    # https://github.com/tailscale/tailscale/issues/14210#issuecomment-4185439890
    environment:
      TS_AUTHKEY: file:/run/secrets/ts_authkey
      TS_STATE_DIR: "var/lib/tailscale"
      TS_USERSPACE: "false"
      TS_EXTRA_ARGS: "--ssh"
      TS_ENABLE_HEALTH_CHECK: "true"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz" ]
    volumes:
      - tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    networks:
      - games_network_tailscale
    restart: unless-stopped

  traefik:
    image: traefik:v3.6.13
    container_name: games_server_traefik
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: "Australia/Sydney"
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      LEGO_DISABLE_CNAME_SUPPORT: "true"
    depends_on:
      - tailscale
    network_mode: service:tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket to watch for Traefik
      - traefik_certs:/certs
      - ./traefik:/etc/traefik/
    env_file:
      - .env
    command:
      - --accesslog=true
      - --api.insecure=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.constraints=Label(`traefik.instance`,`games`) # will ONLY watch for containers with this label
      - --providers.file.watch=true
      - --providers.file.directory=/etc/traefik
      - --ping=true
      - --ping.entrypoint=traefik
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      # Entrypoints for Hytale
      - --entrypoints.hytale.address=:5520/udp
      # TLS
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.caServer=${CA_SERVER}
      - --certificatesResolvers.letsencrypt.acme.storage=/certs/acme.json
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

    labels:
      - tailscale=true
      - traefik.enable=true
      - traefik.instance=games # watch in expected instance
      - traefik.http.routers.traefik.rule=Host(`traefik.${CF_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080

secrets:
  ts_authkey:
    file: ./secrets/ts_authkey

volumes:
  tailscale:
    name: games_server_tailscale
    external: true
  traefik_certs:
    name: games_server_traefik_certs
    external: true

networks:
  games_network_tailscale:
    name: games_server_tailscale
    external: true