name: hytale
services:
  tailscale:
    image: tailscale/tailscale:v1.96.5
    hostname: hytale
    container_name: hytale_tailscale
    env_file:
      - .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--ssh
      - TS_ENABLE_HEALTH_CHECK=true
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz" ]
    networks:
      - tailscale
    volumes:
      - tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  traefik:
    image: traefik:3
    container_name: hytale_traefik
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Australia/Sydney
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - LEGO_DISABLE_CNAME_SUPPORT=true
    depends_on:
      - tailscale
    network_mode: service:tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket to watch for Traefik
      - traefik_certs:/certs
      - ./traefik:/etc/traefik/
    command:
      - --accesslog=true
      - --api.insecure=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.watch=true
      - --providers.file.directory=/etc/traefik
      - --ping=true
      - --ping.entrypoint=traefik
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      # TLS
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.caServer=${CA_SERVER}
      - --certificatesResolvers.letsencrypt.acme.storage=/certs/acme.json
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    labels:
      - tailscale=true
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.hytale.${CF_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  auth:
    image: hybrowse/hytale-session-token-broker:1.0.0
    container_name: hytale_auth
    env_file:
      - .env
    environment:
      HYTALE_SESSION_TOKEN_BROKER_BEARER_TOKEN: "" # optional
    volumes:
      - hytale_auth_data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - hytale_internal
      - hytale_auth_external
    healthcheck:
      test: wget -qO - http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    image: hybrowse/hytale-server:1.0.0
    container_name: hytale_server
    depends_on:
      - auth
    stdin_open: true
#    Only for debugging stack on Macbook
    platform: linux/amd64
    tty: true
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - ./hytale-data:/data
    ports:
      - "5520:5520/udp"
    environment:
      - HYTALE_SESSION_TOKEN_BROKER_ENABLED=true
      - HYTALE_SESSION_TOKEN_BROKER_URL=http://auth:8080
      - HYTALE_SESSION_TOKEN_BROKER_TIMEOUT_SECONDS=10
      - SERVER_ACCEPT_EARLY_PLUGINS=true
      - HYTALE_AUTO_DOWNLOAD=true
      - SERVER_BIND=0.0.0.0:5520
      - SERVER_BACKUP_DIR=/hytale/backups
      - SERVER_BACKUP_INTERVAL=10
      - SERVER_MAX_VIEW_RADIUS=12
      - HYTALE_BACKUP_FREQUENCY_MINUTES=30
      - HYTALE_BACKUP_ARCHIVE_MAX_COUNT=5
    networks:
      - hytale_internal
      - tailscale
    labels:
      - tailscale=true
      - traefik.enable=true
      - traefik.udp.routers.hytale.rule=Host(`hytale.${CF_DOMAIN}`)
      - traefik.udp.routers.hytale.entrypoints=hytale
      - traefik.udp.services.hytale.loadbalancer.server.port=5520

volumes:
  tailscale:
    name: hytale_tailscale
    external: true
  traefik_certs:
    name: hytale_traefik_certs
    external: true
  hytale_auth_data:
    name: hytale_auth_data
    external: true

networks:
  hytale_internal:
    name: hytale_internal
    internal: true

  hytale_auth_external:
    name: hytale_auth_external

  tailscale:
    name: hytale_tailscale
