name: homelab
services:
  tailscale:
    extends:
      file: ../shared/tailscale-traefik.compose.yml
      service: tailscale
    env_file:
      - .env

  traefik:
    extends:
      file: ../shared/tailscale-traefik.compose.yml
      service: traefik
    env_file:
      - .env

  arcane:
    image: ghcr.io/getarcaneapp/manager:v2.12.0
    container_name: arcane
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3552:3552"
    networks:
      - tailscale
    secrets:
      - arcane-encryption-key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - arcane-backups:/backups
      - ../games/hytale:/app/data/projects/hytale
      - ../games/valheim:/app/data/projects/valheim
      - ../games/ts_traefik:/app/data/projects/ts_traefik
      - ./:/app/data/projects/internal
    environment:
      - APP_URL=http://localhost:3552
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=file:/run/secrets/arcane_encryption_key
      - LOG_LEVEL=info
      - LOG_JSON=false
      - OIDC_ENABLED=false
      - DATABASE_URL=file:data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate
    labels:
      - tailscale=true
      - traefik.enable=true
      - traefik.instance=homelab # watch in expected instance
      - traefik.http.routers.arcane.rule=Host(`${ARCANE_SUBDOMAIN:-arcane.ts}.${CF_DOMAIN}`)
      - traefik.http.routers.arcane.entrypoints=websecure
      - traefik.http.routers.arcane.tls.certresolver=letsencrypt
      - traefik.http.services.arcane.loadbalancer.server.port=3552

secrets:
  ts-authkey:
    file: ./secrets/ts_authkey
  cf-dns-api-token:
    file: ./secrets/cf_dns_api_token
  arcane-encryption-key:
    file: ./secrets/arcane_encryption_key

# Model IDs align with what is defined in the base compose
volumes:
  tailscale:
    name: homelab_tailscale
    external: true
  traefik-certs:
    name: homelab_traefik_certs
    external: true
  arcane-data:
    name: arcane_data
    external: true
  arcane-backups:
    name: arcane_backups
    external: true

networks:
  tailscale:
    name: homelab_tailscale
    external: true
